services:
  db-juridico:
    image: postgres:15
    container_name: postgres-juridico
    environment:
      POSTGRES_USER: ${DB_USER:-villalobos_admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password123}
      POSTGRES_DB: ${DB_NAME:-sistema_juridico}
    ports:
      - "${DB_PORT_EXT:-5433}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 1G   
          cpus: '0.50' 

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-juridico
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-ricardo@juridico.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS:-admin}
    ports:
      - "5050:80"
    depends_on:
      - db-juridico
    deploy:
      resources:
        limits:
          memory: 1G   
          cpus: '0.50' 

volumes:
  postgres_data: